### ISSUE TITLE
[RFC] App Test

### ISSUE THREAD

**Issue by wisley7l** [ecomplus/cloud-commerce#151]
Issue para descrevemos ideias, frameworks e o que deveremos fazer para implementarmos os testes para os apps no Cloud-commerce

## O que fazer:
- [x] Firebase emullator in GitHub Actions
- [ ] ...

**Comment by wisley7l** [comment]
lib de teste "nativa" no node 18. 
https://nodejs.dev/en/api/v18/test/

**Comment by leomp12** [comment]
FYI https://github.com/firebase/quickstart-testing
